### ISSUE TITLE
Make case insensitive

### ISSUE THREAD

**Issue by collinkueter** [Zariem/deep-profanity-filter#5]
If I have this text `Darn veggie eaters are eating Grass again out of a brokeN donkey trouGh.`

I would expect the string after calling `censorText` to be `D**n v***** *******s are eating G***s again out of a b****N donkey t****h.` 

but it is however this: `Darn v***** *******s are eating Grass again out of a brokeN donkey trouGh.`

wordlist contains: [darn, veggie eaters, grass, broken, trough]

please make this case insensitive.

**Comment by Zariem** [comment]
Should be fixed in version 2.2.0.
Check out the new setting called `inputPreprocessMethod`. Per default it's now set to `InputPreprocessMethod.CaseInsensitive`.

If you wish to filter fancy unicode characters too (see `textToLatin(...)`), you can do so by using `InputPreprocessMethod.Thorough`, at the cost that phrases containing such special characters being output in latin characters and lower case.

https://github.com/Zariem/deep-profanity-filter/commit/0c39412db388d4ba0462f9c44b58c5d7411b4b54

Let me know if there's anything else that needs fixing :)
