### ISSUE TITLE
What about duplications

### ISSUE THREAD

**Issue by rafal-ksiazek-rmtcfm-com** [Zariem/deep-profanity-filter#6]
Hi, first of all your package is awesome!

Q: what about duplications of some letters? Ie. Kitttttttttty if kitty is forbidden?

**Comment by Zariem** [comment]
Thanks <3 I'm glad the package can be of use to you!

I haven't yet considered letter duplication. Not sure why, but I do assume that it could cause a whole bunch of false positives, depending on the language and the implementation, which is why I might have avoided it in the past.

What is your use case? Are common false negatives usually related to the duplication of letters that appear twice right next to each other (i.e. "tt" in "kitty" -> "kittty") or are they also related to other letters in the word that only appear once? (i.e. "i" in "kitty" -> "kiiiiitty" or "y" in "kitty" -> "kittyyyyyy")

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
Our use case is "cat" => "caaaaaaaat"

**Comment by Zariem** [comment]
Just for specific characters in a word, or for all characters in all words?
- cat -> ccccccat/caaaat/cattttt/ccccaaattt ?
or just cat -> caaaat (with control over which character repeats?)

I'm thinking there might be a way to add some mini-regex-functionality (a special character such as "+") within the word, such as specifying the word as "ca+t" or something. I'd just need to make sure that this would not break my current system.
Would this help your use-case?

I'm just thinking that counting any and all repeat letters as a form of circumvention (without specifying which ones specifically need to be tested for) would lead to too many false positives, so there should probably be some user control in which letters are repeatable.

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
We have right now one case with caaaat but I think the solution should take into account all cases: cccat, caaat, cattt, cccaaat, cccattt, cccaaattt

I was thinking about removing duplicates by simple regex replace to achieve from cccaaattt: 
caat, ccat, catt, cat -> and test them separately 

But approach step by step is also good - so let's first check the caaat => cat / caat or kitttttty => kitty / kity

**Comment by Zariem** [comment]
Imagine you have a word with repeat characters (for example "loot") that also forms a valid word if you remove the repeat characters (in that case "lot") - removing all repeat characters in your preprocessing will potentially misinterpret your word and cause a false positive result.

It's difficult to find examples for false positives by just thinking really hard (most times you'll just end up finding them by your code triggering false positives as time passes). In this case, loot and lot are both not necessarily harmful words, but I've come across one case in which it might backfire:

In Dutch, the word for "tree" is "boom" and the word for "bomb" is "bom", in that case someone might want to put the word "bom" on a bad word list, but if you preprocess and remove repeat characters before testing whether the content is bad or not, you'll always consider anyone talking about trees is actually talking about bombs. Not ideal.

So if we just remove any and all repeating characters as part of the check for circumventions, it'll likely backfire on a lot of people, especially since we cannot assume in which language this library is being used.

What I could see coming of use would be a regular expression that reduces repeat characters of 3 or more characters to 2 repeated characters. (Depending on the language used, however, this might still misfire. For English this might be alright to do.)
For example, the following regular expression can serve that purpose:
`string.replace(/(\w)\1{3,}/g, '$1$1')`
It first matches any word character `(\w)`, then picks the last matched character `\1` and sees if it occurs 3+ times in sequence `{3,}`. The string.replace function then replaces it with twice the matched character `$1`.

I think this might be possible to add as a preprocessing option to my library. If you really want to reduce any repeat character to 1 singular occurrence of that character, try:
`string.replace(/(\w)\1{1,}/g, '$1')`
But do so at your own risk of false positives.

However, I can also look into adding a way to give people control over checking for repeat characters, such as a '+' notation in my accepted inputs. But this might take a moment, since I'm currently looking into another thing with this library.

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
Thank you very much for this analysis. I didn't think that we can do it ourselves and test the library for each variant of the word.

We use the library to verify usernames, so we can point out to someone who wrote booom instead of boom - that this is a potentially illegal word and he must change it.

**Comment by Zariem** [comment]
Working on this, I realised that the regular expression I gave was slightly off (thanks to testing for showing me this flaw lol):
`string.replace(/(\w)\1{3,}/g, '$1$1')` matches characters appearing 4+ times instead of 3+ times. (So "heeeelllooo" would get changed to "heelllooo" instead of "heelloo".) 
This is because the character is matched once with `\w` and then _repeat matched_ another 3 or more times with `\{3,}`

So to reduce subsequent occurrences of the same character to 2 occurrences you'll need:
`string.replace(/(\w)\1{2,}/g, '$1$1')`.

I've added this now as a function in my library (v.2.4.0): `reduceRepeatCharacters(inputText: string, maxAllowedCharsInSequence: number = 2)` and integrated it into the `censorText` function as input `reduceRepeatCharactersTo?: number` (v.2.5.0).

Feel free to use it 😊 👍 

I'll have to update the documentation about this in a further patch update (probably upcoming v.2.5.1 or so.)
I haven't yet investigated adding a '+' notation to the input.

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
I was thinking about such method:

```
function generateValidVariants(input) {
  const matches = input.match(/(.)\1*/g);  // Group consecutive repeating letters
  let results = [];

  function generate(current, index, twoUsed) {
    if (index === matches.length) {
      results.push(current);
      return;
    }

    // Add one letter
    generate(current + matches[index][0], index + 1, twoUsed);

    // Add two letters if this option hasn't been used yet
    if (!twoUsed) {
      generate(current + matches[index][0] + matches[index][0], index + 1, true);
    }
  }

  generate('', 0, false);
  return results;
}
```

```
// Example usage
const word = "cccaaattt";
console.log(generateValidVariants(word));
```

It will produce: ['cat', 'catt', 'caat', 'ccat'] -> and these words need to be checked ... I don't care about false positive, if someone will use more than 2 chars - it's his fault :)

**Comment by Zariem** [comment]
This would however also create `['cat', 'catt', 'caat', 'ccat']` for the input string `'cat'`, so I am not sure what you are trying to accomplish with this. (Plus, it is missing `['caatt', 'ccatt', 'ccaat', 'ccaatt']`, is that intentional?)

If these are the words you want to add to your bad word list and then using `reduceRepeatCharacters(inputString, 2)` on your input and check for bad words `['cat', 'catt', 'caat', 'caatt', 'ccat', 'ccatt', 'ccaat', 'ccaatt']` would do the job. However, that's really only feasible for short words ('cat' has 3 letters), as the size of this list would grow exponentially with the amount of characters in the word you're looking to match, think of all the variants "kittycat" would generate. 🤯 

Or if you _know_ that you want to check _all_ variants, using `reduceRepeatCharacters(inputString, 1)` and checking for the bad word `'cat'` would be most efficient, especially if you don't care about false positives and/or choose your word list wisely.

**Comment by Zariem** [comment]
I'll close this issue for now, since I've added some functionality that can help your specific use case.

I currently don't have the availability to implement something more sophisticated to deal with duplicate letters (thinking of a '+' notation such as testing for 'kitt+y') but since `reduceRepeatCharacters` likely fulfils the requirement of your specific use case I'll put the more complex idea on the future log.
